title: Codeman 的网络日志
name: Codeman
email: liuz_geek@163.com
description: >-
  阅读、书写和编码，输出是最好的学习方法。
baseurl: ""
url: "https://www.1zh.tech"
plugins:
  - jekyll-sitemap
github_username: liuzhuan

markdown: kramdown
highlighter: rouge

permalink: pretty
