baseURL = 'https://www.1zh.tech/'
languageCode = 'zh-CN'
title = 'Codeman 的数字笔记'
theme = 'papermod'

[params]
ShowToc = true
author = 'Codeman'
dateFormat = '2006-01-02'
showCodeCopyButtons = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ['title', 'permalink', 'summary', 'content']

[params.editPost]
URL = 'https://github.com/liuzhuan/liuzhuan.github.io/edit/main/content'
Text = '纠错'
appendFilePath = true

[caches]
[caches.images]
dir = ':cacheDir/images'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[[menu.main]]
name = 'Search'
url = 'search'
weight = 10

[[menu.main]]
name = 'About'
url = 'about'
weight = 8